mappings:
  'Primary_Key':
  'Earner_Name': 'Earner Name'
  'Earner_ID': 'Earner NPN'
  'Agent_Name': 'Writing Broker Name'
  'Agent_ID': 'Writing Broker NPN'
  'Commission_Amount': 'Payment Amount'
  'Commission_Period': 'Pay Period'
  'Carrier_Name': 'Carrier'
  'Enrollment_Type': 'Payment Type'
  'Plan_Name': 'Plan Name'
  'Member_Name': 'Member Name'
  'Member_ID': 'Centene ID'
  'Effective_Date': 'Effective Date'
  'Cycle_Year': 'Cycle Year'
  'Earner_Type':